### ISSUE TITLE
Add item issue

### ISSUE THREAD

**Issue by malhal** [matteom/ToDoList#2]
[the article about this MVC design](https://www.smashingmagazine.com/2016/05/better-architecture-for-ios-apps-model-view-controller-pattern/) appears to have left out the communication from Model to Controller to notify of new data. Looks like it reloads the whole table when one item is added. Instead, a new row could be inserted into the table, which is also more efficient.

**Comment by matteom** [comment]
That is true, but I wanted to keep the example simple on purpose, because the point was to look at the architecture more than all the functionality offered by table views.
